# Generated by Django 3.0 on 2021-02-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210204_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status_completed',
            field=models.NullBooleanField(),
        ),
    ]
