# Generated by Django 3.0 on 2021-02-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_status_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status_completed',
        ),
    ]
