# Generated by Django 3.0 on 2021-02-07 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0007_appraisal_plans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='rate',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Okay', 'Okay'), ('Bad', 'Bad'), ('Not Satisfactory', 'Not Satisfactory')], max_length=50),
        ),
    ]
